name: next-js-server
services:
    app:
        image: brightky/ecommerce-client:${IMAGE_VERSION}
        container_name: client-docker
        env_file:
            -   .env
        ports:
            -   '80:3000'
        environment:
            - NODE_ENV=production
        