name: next-js-server
services:
    app:
        build:
            context: .
        container_name: client
        env_file:
            -   .env
        ports:
            -   '80:3000'
        environment:
            - NODE_ENV=production
        