name: CI-CD
env:
    NODE_VERSION: '20.x'
    FOLDER: /home/brightky/applications/e-commerce/client
    IMAGE: client
    IMAGE_VERSION: latest
on:
    workflow_dispatch:
    push:
        branches:
            - main
jobs:
    create-folder:
        name: Create folder
        runs-on: ubuntu-latest
        steps:
            - name: Create folder
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.HOST }}
                  port: 22
                  username: ${{ secrets.USERNAME }}
                  key: ${{ secrets.KEY }}
                  script: |
                    mkdir -p  ${{ env.FOLDER }}
    tests:
        name: tests
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [18.x, 20.x, 21.x]
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npm ci
            - run: npm test

    copy:
        name: copy-files
        runs-on: ubuntu-latest
        needs: create-folder
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Get changed files
              id: changed-files
              uses: tj-actions/changed-files@v35
              with:
                  since_last_remote_commit: true
                  separator: ","
            - name: copy files on server VPS
              uses: appleboy/scp-action@v0.1.7
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  port: 22
                  key: ${{ secrets.KEY }}
                  source: ${{ steps.changed-files.outputs.all_changed_files }}
                  target: ${{ env.FOLDER }}
    build:
        name: build and deploy
        runs-on: ubuntu-latest
        needs:
            - tests
            - copy
        steps:
            - name: run docker compose with ssh
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  port: 22
                  key: ${{ secrets.KEY }}
                  script: |
                        docker compose -f ${{ env.FOLDER }}/docker-compose.yml stop || true
                        docker compose -f ${{ env.FOLDER }}/docker-compose.yml rm -f || true
                        docker compose -f ${{ env.FOLDER }}/docker-compose.yml up -d