name: 'Try it with docker'
on:
    workflow_dispatch:
env:
    NODE_VERSION: '20.x'
    FOLDER: /home/brightky/applications/e-commerce/client
    IMAGE: ecommerce-client
    IMAGE_VERSION: latest
jobs:
    